### ISSUE TITLE
Unable to Visualize map & navgraphs in RViz

### ISSUE THREAD

**Issue by ganatsh** [open-rmf/rmf_demos#112]
### Required information:

- Operating system and version: Ubuntu 20.04
- OpenRMF installation type: From source, binaries
- OpenRMF version or commit hash: foxy
- ROS installation type: binaries
- Package or library, if applicable: N/A

### Description of the bug
When we are trying to run the RMF office demo. We are not able to visualize the map and navgraph in the RViZ window that opens up.
Where as when we try to run the RMF office demo along with the gazebo. We are able to visualize the map and navgraph in RViZ window.
Sometimes the map and navgraph is visible when we reboot our system, and then run the RMF. After that when we try to run the RMF file, It doesn't shows the map and navgraph.

### Steps to reproduce the bug

1. Launch RMF using `ros2 launch rmf_demos office_demo.launch.xml`
2. After that, when the RViZ Window open's up we can't visualize the map.
3. Launch RMF using `ros2 launch rmf_demos_gz office_demo.launch.xml`
4. We can visualize the map and navgraph in RViZ

### Expected behavior
When we launch the RMF demo file. It open ups a RViZ window in order to show the
map as well as the Navgraph for particular robots.

![Screenshot from 2021-11-25 11-46-58](https://user-images.githubusercontent.com/92590463/143390867-fb493403-18d0-44ef-9b2b-a79f19e75daf.png)

### Actual behavior
What actually is happening is that, When ever we try to run the RMF demo file. It open ups the RViZ
window but is not showing the map and the Navgraph for the robots. Whereas just keeps on displaying a black screen in the RViZ window. Without anything to display.

![Screenshot from 2021-11-25 11-58-50](https://user-images.githubusercontent.com/92590463/143391053-5e3e1c5d-150a-45ae-8440-7a0a1659b467.png)

**Comment by Muhammad-asem** [comment]
try to change the `<arg name="use_sim_time" default="false"/> ` from **false** to **true** `<arg name="use_sim_time" default="true"/>`  in  the ` /opt/ros/foxy/share/rmf_demos/office.launch.xml`  file.

**Comment by ganatsh** [comment]
Thank You, Asem it worked for me.

**Comment by Yadunund** [comment]
Hi @ganatsh ,

The launch files in `rmf_demos_gz` are supersets of those in `rmf_demos`. The latter ones can be thought of as launch files for testing with real robots while the ones in `rmf_demos_gz` launch up a gazebo environment for testing in simulation. So you `Steps to Reproduce` is not a valid workflow. You would either launch from `rmf_demos`  or `rmf_demos_gz` depending on whether you're testing in the real world or simulation, but not both. 

Having said that, it is strange that you were not able to visualize the map and traffic lanes in RViz after running `ros2 launch rmf_demos office_demo.launch.xml`. Even with `use_sim_time` set to `false`, you should be able to see these in RViz. Are you able to share the contents on your `office_demos.launch.xml` file?

**Comment by NaglaShubham** [comment]
Thank-you for replying @Yadunund ,

We actually are using the files, in a similar manner that you have mentioned above. 

I also am having the same doubt. That it should be working, with `use_sim_time` set to `false`.

Yes, i can share the contents of `office_demos.launch.xml`. But, i don't think we made any changes to the file itself
[office.ODT](https://github.com/open-rmf/rmf_demos/files/7658480/office.ODT)
You can find the contents of the office.launch.xml in the above attached file.

**Comment by Yadunund** [comment]
Thanks for sharing. There file looks okay. There was a similar discussion [here](https://github.com/open-rmf/rmf/discussions/118). Looks like the issue was DDS related for another user. Perhaps you could try switching DDS implementations as suggested to see if that solves the problem.

**Comment by HappySamuel** [comment]
Hi

If i am using the system on real robot, i shall set use_sim_time to false, right? But i couldn't see anything on RVIZ, except `/fleet_markers`. Any idea how to have others (`/floorplan`, `/map_markers`, `/schedule_markers`, `/building_systems_markers`) to be seen?

Best,
Samuel

**Comment by Yadunund** [comment]
@HappySamuel ,

Did you make sure to set `use_sim_time` to `false` for all the nodes that you launched?

**Comment by HappySamuel** [comment]
Hi @Yadunund 

Yes all my nodes are having `use_sim_time` with `false`. What else shall i check?

Best,
Samuel

**Comment by Yadunund** [comment]
Does the `Map Name` in your SchedulePanel in RViz match the level name in the navgraph exported from `rmf_traffic_editor`? For example, if you defined a level named "Level1" in traffic editor with navigation lanes for your robot and you're feeding in this navigation graph to your fleet adapter, then the `Map Name` textbox should be set to this value.

**Comment by HappySamuel** [comment]
Hi @Yadunund 

Yes, `map name` in SchedulePanel on RVIZ match the level name in navgraph exported from `rmf_traffic_editor`.

Best,
Samuel

**Comment by maurya3** [comment]
Hi Guys,
I resolved this error by downgrading int numpy version below 1.16. There is some error in numpy. 
`"AttributeError: module 'numpy' has no attribute 'asscalar'"
`
because of
 `Deprecated since version 1.16: Deprecated, use numpy.ndarray.item() instead.
`

**Comment by josh-001** [comment]
i am unable to vizualize map of the area in rviz but i am getting nav_graph like these
![Screenshot from 2024-11-18 10-38-04](https://github.com/user-attachments/assets/b954f94d-788f-4dfd-a30a-0f82fe2add92)
map name in Schedule panel and level name in traffic editor both are same.
