### ISSUE TITLE
Modify README to be more explicit about not mixing binary / source install?

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf_demos#117]
We could perhaps add a disclaimer not to mix source / binary installs, to prevent accidental build :fire:  .

**Comment by Yadunund** [comment]
Good idea. Would it be better to add the note to the installation instructions in the [open-rmf/rmf repository](https://github.com/open-rmf/rmf#binary-install) since the README here is more focused on running the demos?

**Comment by cnboonhan** [comment]
ah yes, i should change this, thank you!
