### ISSUE TITLE
office demo delivery task

### ISSUE THREAD

**Issue by HughYZJD** [open-rmf/rmf_demos#118]
In the example office, I try to run the 'delivery' task. The robot stops at the pickup waypoint. What command should I send to make it run to the dropoff point,thanks!

**Comment by Yadunund** [comment]
Hi there,

Instructions to send a delivery task for the office world are available in the README [here](https://github.com/open-rmf/rmf_demos#office-world). Scroll down to "Submit a task via CLI"
```
ros2 run rmf_demos_tasks dispatch_delivery -p pantry -pd coke_dispenser -d hardware_2 -di coke_ingestor --use_sim_time
```
