### ISSUE TITLE
Fleet Adapter throws exception sometimes after office_loop.launch.xml

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf_demos#133]
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type: 
  - Source
- OpenRMF version or commit hash: 
  - main
- ROS distribution and version:
  - galactic
- ROS installation type:
  - binaries
- Package or library, if applicable:
  - rmf_fleet_adapter

### Description of the bug

Full control fleet adapter throws an exception sometimes in `office.launch.xml` after `office_loop.launch.xml` is called. Exception is 

```
[full_control-13] terminate called after throwing an instance of 'std::invalid_argument'
[full_control-13]   what():  Battery State of Charge needs to be between 0.0 and 1.0.
```

Gist: [here](https://gist.github.com/aaronchongth/e0c724cda7cc82bdf9f045fdd1bc566e)

### Steps to reproduce the bug

```bash
ros2 launch rmf_demos_gz office.launch.xml

# in another terminal
ros2 launch rmf_demos office_loop.launch.xml
```

### Additional information

* this does not happen all the time, probably some race conditions happening somewhere?
* I am also using an underpowered laptop, this might not occur on beefier machines

**Comment by mxgrey** [comment]
I believe this issue has been resolved by an earlier PR.
