### ISSUE TITLE
Fatal error for rmf_traffic_schedule-1

### ISSUE THREAD

**Issue by choobacca-bacca** [open-rmf/rmf_demos#151]
### Required information:

- Operating system and version: Ubuntu 20.04
- OpenRMF installation type: From source, following install in https://github.com/open-rmf/rmf for galactic
- OpenRMF version or commit hash: latest commit, 92972bffbdb3c4e8e4bfb8b1238047d876c07f38
- ROS distribution and version: galactic
- ROS installation type: from binary
- Package or library, if applicablle: N/A

### Description of the bug
get error `[rmf_traffic_schedule-1] [FATAL] [1660195044.439489807] [rmf_traffic_schedule_primary]: Failed to correctly load participant registry: yaml-cpp: error at line 9, column 16: bad conversion` in terminal

No map displayed in rviz, but the lift and doors are present

### Steps to reproduce the bug
1. Launch RMF using `ros2 launch rmf_demos office_demo.launch`
2. See the error displayed in rviz panel and error message in terminal

**Comment by mxgrey** [comment]
Look for a file called `.rmf_schedule_node.yaml` in the directory that you are launching RMF from. Please copy/paste the contents of that file into a [gist](https://gist.github.com/) and share a link to the gist here. That will help us diagnose if something has gone wrong within RMF to lead to this error.

After you've done that, delete the file and everything should go back to working as normal.

We should improve the error message to specify the file location and to recommend fixing or deleting it as a solution to this error.

**Comment by choobacca-bacca** [comment]
`- operation: Add
  participant_description:
    name: caato_1
    group: caato
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.5
        - 0.6`
So thank Dr.Grey, it was resolved after deleting this file.
