### ISSUE TITLE
rmf demos connection error

### ISSUE THREAD

**Issue by sajidmohd717** [open-rmf/rmf_demos#174]
### Required information:

- Operating system and version:
  - ubuntu 22.04
- OpenRMF installation type:
  - source install
- OpenRMF version or commit hash
  - we installed it following the instructions on the instructions, current commit hash: 2687cbc59ceb39ff0e3c42c9dc8cb15a80a0ce4b
- ROS distribution and version:
  - we are using ROS humble
- ROS installation type:
  - Installed ROS humble from binary

### Description of the bug

When we run any of the rmf demos launch file like ros2 launch rmf_demos_gz_classic hotel.launch.xml or ros2 launch rmf_demos_gz_classic office.launch.xml, we manage to launch the gazebo world, and we can see rviz. However, the problem is that we arn't able to see the robot on rviz, and we seem to be getting a connection error as seen from the screenshot below.  

### Steps to reproduce the bug

1. Install ubuntu 22.04
2. Install ROS humble
3. install rmf with source
4. run rmf demos (office world, hotel world, etc)

### Expected behavior

Expected behaviour is that we should be able to see yellow dots on rviz which represents the robot and we should not be getting any errors on our terminal.

### Actual behavior

you can see from the screenshot what is error that we got.

### Screenshots

![Screenshot from 2023-02-22 11-28-40](https://user-images.githubusercontent.com/89695946/220515524-72c51b03-7adb-447e-8cc4-8c59264fe192.png)

**Comment by airuchen** [comment]
Same issue. Solved by installing the dependencies : https://github.com/open-rmf/rmf#additional-dependencies

**Comment by Yadunund** [comment]
Thanks for reporting your fix @airuchen 
I'll close this issue for now, feel free to let me know if it still persists.
