### ISSUE TITLE
TypeError: Server.emit() got an unexpected keyword argument 'broadcast'

### ISSUE THREAD

**Issue by RDaneelOlivav** [open-rmf/rmf_demos#177]
## Bug report
TypeError: Server.emit() got an unexpected keyword argument 'broadcast'

### Required information:

- Operating system and version: Ubuntu 22
- OpenRMF installation type:
debians
- OpenRMF version or commit hash
debians
- ROS distribution and version:
humble
- ROS installation type:
by debians

### Description of the bug
When launching the any example that launches the rmf comons, gives this error:

`TypeError: Server.emit() got an unexpected keyword argument 'broadcast'`

This makes the web interface not work.

I tracked the error until here:

[simple_api_server.py](https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos_panel/rmf_demos_panel/simple_api_server.py#L135)

Is there a version that I'm not aware of?

### How to reproduce
execute:

`ros2 launch rmf_demos_gz_classic hotel.launch.xml | grep "Server.emit"`

You should see that error.

### Expected behavior
I would imagine that following this tutorial of installation, there shouldn't  be any errors:
[https://github.com/open-rmf/rmf/discussions/267](https://github.com/open-rmf/rmf/discussions/267)

### Screenshots

![Screenshot from 2023-04-04 18-12-41](https://user-images.githubusercontent.com/4933774/229760802-ff03b73f-7f0b-413d-96a8-c64dcaf52478.png)

### Additional information
I will try to do the same but installing rmf from source but I really don't understand why this could be happening. Hve I done something wrong in the installation?

UPDATE: Did the source installation with the exact same results
UPDATE2: Tried to update the Websockets, like so [ISSUE](https://github.com/open-rmf/rmf_demos/issues/169), same result.

**Comment by RDaneelOlivav** [comment]
Not solved, but seems at least not affects the assignments of tasks and so on. 
Although it continues to not show the tasks in the web interface ( the old one ) . So I imagen I'll close the issue

**Comment by YYZ252** [comment]
I had the same problem and finally solved it by follow the guide of "https://github.com/open-rmf/rmf_demos/issues/169".
```
sudo apt remove python3-websockets 
python3 -m pip install websockets==10.4
python3 -m pip install asyncio 
```
