### ISSUE TITLE
[Other issue]: nav_graphs/0.yaml

### ISSUE THREAD

**Issue by josh-001** [open-rmf/rmf_demos#266]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I opened traffic-editor and I drawed lanes,walls and saved the file after that got a yaml file i will share the files
Traffic-editor:

![Screenshot from 2024-11-15 15-05-02](https://github.com/user-attachments/assets/abe5817b-1017-40e8-8e3b-8bd2da1ed049)

Yaml file:
i am not able to post it here i will shhare you the screen shot of it 
![Screenshot from 2024-11-15 15-08-48](https://github.com/user-attachments/assets/b3d19c7e-184c-43f2-8e8b-407ca3655f8a)

from this yaml i got 0.yaml i did by using below command
**ros2 run rmf_building_map_tools building_map_generator nav /home/research/rmf_ws/src/rmf_traffic_editor/maps/new_map.building.yaml  /home/research/rmf_ws/src/rmf_traffic_editor/maps/**

then  after doing colcon build i didnt get the maps or yaml in  share folder.

anyone who solved this could you reply it or who has experience in this 
thank you.

**Comment by akash-roboticist** [comment]
@josh-001 - please open a discussion regarding this (link in template above), as this is not an issue but rather a how to question.
As for pasting codeblocks please see Github's [guide](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) on markdown syntax
