### ISSUE TITLE
[Bug]: Fleet adapter not starting

### ISSUE THREAD

**Issue by naisama** [open-rmf/rmf_demos#269]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 24.04

### Open-RMF installation type

Binaries

### Open-RMF version or commit hash

jazzy

### ROS distribution

Jazzy

### ROS installation type

Binaries

### Description of the bug

When trying to run any simulation using:
source ~/rmf_ws/install/setup.bash
ros2 launch rmf_demos_gz hotel.launch.xml

I get the following errors
[fleet_adapter-15] Other error for cleanerBotA_2 in get_data: HTTPConnectionPool(host='127.0.0.1', port=22013): Max retries exceeded with url: /open-rmf/rmf_demos_fm/status?robot_name=cleanerBotA_2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efa23545d30>: Failed to establish a new connection: [Errno 111] Connection refused'))

This occurs for each robot in any simulation. I have checked the ports and they are not in use
Is there any service I need to start manually?

Thanks!

P.S: Additional info - I can sent tasks, and the reply is:
ros2 run rmf_demos_tasks dispatch_patrol -p restaurant  L3_master_suite -n 1 --use_sim_time
[INFO] [1733144245.529242338] [task_requester]: Using Sim Time
[INFO] [1733144245.532441902] [task_requester]: Using 'dispatch_task_request'
Json msg payload: 
{
  "type": "dispatch_task_request",
  "request": {
    "unix_millis_earliest_start_time": 0,
    "category": "patrol",
    "description": {
      "places": [
        "restaurant",
        "L3_master_suite"
      ],
      "rounds": 1
    }
  }
}
Got response:
{'state': {'booking': {'id': 'patrol.dispatch-1beccacf08', 'unix_millis_earliest_start_time': 0}, 'category': 'patrol', 'detail': {'places': ['restaurant', 'L3_master_suite'], 'rounds': 1}, 'dispatch': {'errors': [], 'status': 'queued'}, 'status': 'queued', 'unix_millis_start_time': 0}, 'success': True}

### Steps to reproduce the bug

1. Launch demo
source ~/rmf_demos_ws/install/setup.bash
ros2 launch rmf_demos_gz office.launch.xml

**Comment by mxgrey** [comment]
This is almost certainly an issue in your local setup and not something that's being caused by Open-RMF.

Are you using docker or some other containerization in some way? If so, you probably need to configure it to allow programs access to the port.

**Comment by naisama** [comment]
Thanks for the answer! I couldn't find the problem in the configuration, however, I have repeated the installation of OpenRMF using source, and with this option it works correctly.
