### ISSUE TITLE
[Other issue]:  Is there a detailed and comprehensive tutorial for integrating real robots?

### ISSUE THREAD

**Issue by lmmir** [open-rmf/rmf_demos#270]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Is there a detailed and comprehensive tutorial for integrating real robots?

**Comment by akash-roboticist** [comment]
Closing, duplicate of https://github.com/open-rmf/rmf/discussions/569
