### ISSUE TITLE
Non-unique names detected for links in `airport_terminal.world`

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf_demos#73]
### Required information:

- Operating system and version: Ubuntu 20.04
- OpenRMF installation type: Source build
- OpenRMF version or commit hash: main-->
- ROS distribution and version: Foxy
- ROS installation type: binaries

### Description of the bug

During the launch of `airport_terminal.launch.xml`, this error message occurs, specifically targeting the `Table` model, https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Table

It does not affect the simulation, other than the error message showing up. This might be due to some behavior changes in nested `SDF` models.

```bash
[gzserver-14] [Msg] Loading world file [/home/aaron/workspaces/rmf/install/rmf_demos_maps/share/rmf_demos_maps/maps/airport_terminal/airport_terminal.world]
[gzserver-14] Error: Non-unique names detected in <link name='link'>
[gzserver-14]   <collision name='surface'>
[gzserver-14]     <pose>0 0 1 0 -0 0</pose>
[gzserver-14]     <geometry>
[gzserver-14]       <box>
[gzserver-14]         <size>1.5 0.8 0.03</size>
[gzserver-14]       </box>
[gzserver-14]     </geometry>
[gzserver-14]     <surface>
[gzserver-14]       <friction>
[gzserver-14]         <ode>
[gzserver-14]           <mu>0.6</mu>
[gzserver-14]           <mu2>0.6</mu2>
[gzserver-14]         </ode>
[gzserver-14]       </friction>
[gzserver-14]     </surface>
...
```

### Steps to reproduce the bug

```
ros2 launch rmf_demos airport_terminal.launch.xml
```

**Comment by Yadunund** [comment]
@youliangtan is this issue still active?

**Comment by youliangtan** [comment]
The warning doesn't get printout now, I will close this ticket.
