### ISSUE TITLE
test_ackman scenario uses wrong models

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf_demos#87]
test_ackman scenario imports Ambulance as a model, instead of being spawned through traffic map annotation. Consequently, it seems the wrong model ( without slotcar plugin ) is used. 

Vaguely related to https://github.com/open-rmf/rmf_traffic_editor/issues/386 involving some issues with the model download pipeline from fuel.

**Comment by ddengster** [comment]
we switched to `AmbulanceSlotcar` and spawned it as a robot in https://github.com/open-rmf/rmf_demos/pull/86, it should be fixed now
