### ISSUE TITLE
Not all doors in clinic world have a door plugin specified

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf_demos#90]
Some doors in the clinic world do not seem to have plugins assigned. For example: 

https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos_maps/maps/clinic/clinic.building.yaml#L21

Is this intentional? It results in a rather odd visual on rmf-web, where the doors are listed but cannot be controlled.
![door_panel](https://user-images.githubusercontent.com/12628669/133448918-f655324e-377d-42b3-99b9-e0e19de132d5.png)

**Comment by aaronchongth** [comment]
Thanks for picking up on this! Yes, that is intentional as there would be too many plugins running, slowing down the simulation.

How are the doors getting picked up by the dashboard? Is it not through `rmf_door_msgs`?

**Comment by cnboonhan** [comment]
perhaps @koonpeng  or @ChawinTan  will know the best solution :)

**Comment by koonpeng** [comment]
Doors and lifts are gotten from the building map. Doors without a state being published shows `N/A` in the ui.

**Comment by cnboonhan** [comment]
What would you recommend we do in this case?  I'm guessing we could
- Leave it as is
- Render only infrastructure with states
- Rely on state messages to populate the infrastructure tabs 
- ? more possibilities?

**Comment by mxgrey** [comment]
This only impacts simulations, so I would personally suggest leaving it as it is.

**Comment by koonpeng** [comment]
> This only impacts simulations, so I would personally suggest leaving it as it is.

+1

Relating to open-rmf/rmf_ros2#123. A door/lift that we know exists based on the map but is not publishing any states could mean that there is a critical failure (e.g. the node has crashed). Hiding these doors/lifts would be really bad in production.

As a workaround, we can make a "batch" adapter that publishes states for all doors/lifts to avoid spawning too many plugins.

**Comment by cnboonhan** [comment]
That's a great point. If agreeable i'll close this issue but feel free to reopen it.

**Comment by mxgrey** [comment]
> As a workaround, we can make a "batch" adapter that publishes states for all doors/lifts to avoid spawning too many plugins.

If I understand correctly, the issue with having too many plugins isn't that there's excessive publishing, but rather that there would be a lot of excess physics simulation if all the doors are controllable.

When the doors are not controllable, we can set them to "static", so the physics engine just ignores them, but they can't be static if we need to control (open/close) them.
