### ISSUE TITLE
rmf_demos_panel: Download of webpack to location with no permissions

### ISSUE THREAD

**Issue by marcoag** [open-rmf/rmf_demos#92]
### Required information:

- Operating system and version:
  - Ubuntu Focal
- OpenRMF installation type:
  - binaries
- OpenRMF version or commit hash
  - 1.3.0
- ROS distribution and version:
  - galactic
- ROS installation type:
  - binaries
- Package or library, if applicable:
  - rmf_demos_panel

### Description of the bug

When trying to run a demo on an installed version of Open-RMF `rmf_demos_panel` uses this function to try to download the webpack to a location that is relative to the installation of the package:

https://github.com/open-rmf/rmf_demos/blob/513550af993a9c52a55d06c853576dea4c944a86/rmf_demos_panel/rmf_demos_panel/gui_server.py#L32

when using binary packages the user does not have permissions on the installation directory, therefore this fails:

```
[gui_server-13] Check path  /opt/ros/galactic/lib/python3.8/site-packages/rmf_demos_panel/static/dist/app.bundle.js
[gui_server-13] BundleJS File does not exist, Download it from https://open-rmf.github.io/rmf_demos/v1.0.0/app.bundle.js
[gui_server-13] Traceback (most recent call last):
[gui_server-13]   File "/opt/ros/galactic/lib/rmf_demos_panel/gui_server", line 11, in <module>
[gui_server-13]     load_entry_point('rmf-demos-panel==0.0.0', 'console_scripts', 'gui_server')()
[gui_server-13]   File "/opt/ros/galactic/lib/python3.8/site-packages/rmf_demos_panel/gui_server.py", line 77, in main
[gui_server-13]     download_webpack()
[gui_server-13]   File "/opt/ros/galactic/lib/python3.8/site-packages/rmf_demos_panel/gui_server.py", line 51, in download_webpack
[gui_server-13]     open(bundle_path, 'wb').write(response.content)
[gui_server-13] PermissionError: [Errno 13] Permission denied: '/opt/ros/galactic/lib/python3.8/site-packages/rmf_demos_panel/static/dist/app.bundle.js'
```
Alternative solutions to the problem
- Install the webpack somewhere in some config directory in the user's home directory.
- Find alternative ways to distribute the webpack. can this be installed through system packages? any other way?

### Steps to reproduce the bug

1. On a new Ubuntu focal machine install `ros-galactic-rmf-demos-gz`.
2. Run one of the demos, i.e. `ros2 launch rmf_demos_gz office.launch.xml`.

### Expected behavior
The demo run as per normal and the dashboard panel should be accessible through a web browser at http://localhost:5000

### Actual behavior
The dashboard panel is not found in the browser.

**Comment by youliangtan** [comment]
If we download the webpack during compile-time, and pack this within the release. Will this work?

**Comment by marcoag** [comment]
If we do it at compile time then it will be included in the binary and installed so it will work. I'm not sure if it's ideal to ship a webpack inside the package but I guess it's a solution.
